### PR TITLE
Some little correction in the hungarian translation

### PR DESCRIPTION
**Pull request by GrayFarkas**
I was corrected some hungarian letter by grammatical and modify some words for better interpreting.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
Thanks, @GrayFarkas!

**Comment by PiotrMachowski** [comment]
I have just uploaded some translations-related changes (translating values for tiles), do you want to include them in Hungarian translations as well?
[related change](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/commit/b58a226bf07909c4b2c9d18660f447edc8e44d87#diff-12d32693d296e25fbdd26131c267fc760fdb6dc1f558b4e426b97fab9e1f82a1R132)

**Comment by GrayFarkas** [comment]
Exactly, now I will check the hu.json and if I find something I will fix it.

**Comment by PiotrMachowski** [comment]
You can edit this file: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/dev/src/localize/languages/hu.json

**Pull request merged**
