### PR TITLE
2.0.10

### PR DESCRIPTION
**Pull request by PiotrMachowski**

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
@jrada @konni @Rittsel @tzagim @nova12324 @gsotiriou @robin-lion @Gooman-rus @Kejszijo @fbirollo @michelotten @thorsten @Nicholaiii @HepoH3 @demey @MakerMark @PedroDelCargo @LeandroIssa

You might want to adjust translations to include the latest features

**Comment by Nicholaiii** [comment]
Should I just send a PR to dev?

**Comment by HepoH3** [comment]
> You might want to adjust translations to include the latest features ([example](src/localize/languages/en.json))

Can you tell wich differences between "spot cleaning", "zone cleaning" and "segment cleaning"? First one is cleaning of some point, second is cleaning of a room, third is cleaning of the rectangle you've selected?
What differences between "remote control active" and "manual mode" ? I believe one of this is for controlling vacuum via remote controller in the mi home app, but has no clue which one and what to do with last one.

**Comment by PiotrMachowski** [comment]
@Nicholaiii exactly

@HepoH3 
"spot cleaning" - cleaning a square around a point
"zone cleaning" - cleaning selected rectangle
"segment cleaning" - cleaning a room (by id)

"remote control active" and "manual mode" might refer to the same thing for different models

**Pull request merged**
