### PR TITLE
fix: remove uses of replaceAll that don't work on older devices/browsers

### PR DESCRIPTION
**Pull request by mgabor3141**
This PR fixes https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/411

Tested and the button is now working on my old Nexus 7, where it wasn't working before.

### CODE REVIEW

**Comment by FHeilmann** [comment]
@mgabor3141 could you send me the artifact of your build? I was hoping to fix this on my end as well.

**Comment by PiotrMachowski** [comment]
@FHeilmann artifacts are available [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/pull/513/checks)

**Comment by FHeilmann** [comment]
> @FHeilmann artifacts are available [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/pull/513/checks)

I must be blind. Thanks a lot! :)

**Comment by PiotrMachowski** [comment]
@mgabor3141 I think I would prefer to use a polyfill instead (e.g. [this one](https://vanillajstoolkit.com/polyfills/stringreplaceall/)

**Comment by nios87** [comment]
I'm in the same boat. Older Android device. Will this  be merged ?

**Comment by snios** [comment]
> @mgabor3141 I think I would prefer to use a polyfill instead (e.g. [this one](https://vanillajstoolkit.com/polyfills/stringreplaceall/))
I did try that polyfill but sadly it did not work. So if anyone has a very good polyfill and is used to working with polyfills feel free to  pitch in. Otherwise the quick solution would be to use replace instead of replaceAll for comapbility with older browsers?

**Comment by PiotrMachowski** [comment]
@snios which device do you have?

**Comment by snios** [comment]
> 

Chrome 81.0.4044.138  on Android 4.2.2

**Comment by PiotrMachowski** [comment]
Woah, that's pretty ancient... Does HA work for you without any problems?

**Comment by PiotrMachowski** [comment]
@snios can you check which ES version does your browser support? (using [this snippet](https://stackoverflow.com/a/75325970))

**Comment by PiotrMachowski** [comment]
Ok, I'll close this PR because it doesn't actually fix the problem in all places (usage in `utils.ts` is incorrectly migrated). I have tried to make it work with a polyfill instead.

**Pull request closed without merging**
