### PR TITLE
Update rand256_valetudo_re.json

### PR DESCRIPTION
**Pull request by sca075**
added "id_type": "number" to avoid failure of the segment cleaning command send via MQTT

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
I have checked and IDs can also be strings (room numbers)
https://github.com/rand256/valetudo/wiki/MQTT-API
Have you checked if this approach will work?

**Comment by sca075** [comment]
Piotr the docs in Rand256 for segmented_cleanup not zones are integers. We need the segments ID only in integer.

**Comment by PiotrMachowski** [comment]
Yeah, room ids have to be provided as numbers, but according to the documentation it should also be possible to send room name as string instead room id:
```json
{
"command": "segmented_cleanup",
"segment_ids": [
    16,
    "Room Name 1",
    18
],
"repeats": 2,
"afterCleaning": "Base"
}
```

**Comment by PiotrMachowski** [comment]
> I'll adjust the code to fallback to string if it's not possible to convert it to a number, it should handle both cases after that

Done, if you want to you can test it using version from [this build](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/actions/runs/6784669531)

**Pull request merged**
