### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by HepoH3**
I have doubts about last element:
`two_finger_pan` means that I can scroll smthing with two fingers gesture?

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
> I have doubts about last element:
> `two_finger_pan` means that I can scroll smthing with two fingers gesture?

Yup, it enables moving map with 2 fingers instead of 1

**Comment by HepoH3** [comment]
> 
> 
> > I have doubts about last element:
> > `two_finger_pan` means that I can scroll smthing with two fingers gesture?
> 
> Yup, it enables moving map with 2 fingers instead of 1

Moving in any direction (not just horizontal/vertical)?

**Comment by PiotrMachowski** [comment]
> > > I have doubts about last element:
> > > `two_finger_pan` means that I can scroll smthing with two fingers gesture?
> > 
> > 
> > Yup, it enables moving map with 2 fingers instead of 1
> 
> Moving in any direction (not just horizontal/vertical)?

Well, you can't rotate the map this way, but you can move map diagonally

**Comment by HepoH3** [comment]
> 
> 
> > > > I have doubts about last element:
> > > > `two_finger_pan` means that I can scroll smthing with two fingers gesture?
> > > 
> > > 
> > > Yup, it enables moving map with 2 fingers instead of 1
> > 
> > 
> > Moving in any direction (not just horizontal/vertical)?
> 
> Well, you can't rotate the map this way, but you can move map diagonally

I see, I need to make a few adjustments.

**Comment by HepoH3** [comment]
Done

**Comment by PiotrMachowski** [comment]
Please adjust README and localize.ts as well (Like in #166)

**Comment by HepoH3** [comment]
> 
> 
> Please adjust README and localize.ts as well (Like in #166)

Done

**Pull request merged**
