### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fbirollo**
Spanish translation

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
I think your pull request is missing some changes 😃

**Comment by fbirollo** [comment]
Sorry, I'm new in GitHub. I do the spanish translation for your integration.

**Comment by PiotrMachowski** [comment]
No problem :) the easiest way to do it would be to go to your fork and click <dot> on your keyboard. It will open a nice online editor

**Comment by fbirollo** [comment]
I did all the steps in the document, but I understood that the last step had to do it here.

**Comment by PiotrMachowski** [comment]
No, you have to include all changes in one PR

**Comment by fbirollo** [comment]
Thanks!

**Pull request closed without merging**
