### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by Dis90**
Not complete translation but almost.

Edit. Now completely translated to Finnish.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
Do you want to create a second PR with the rest of changes?

**Comment by Dis90** [comment]
I can update this PR later tonight if you want complete translation 😊

**Comment by Dis90** [comment]
@PiotrMachowski Everything is now translated.

**Comment by PiotrMachowski** [comment]
> Edit. One line is untranslated. What does this mean?
> `Two finger pan (optional)`

It enables a mode in which you have to use two fingers to move the map in touch mode (instead of just one)

**Comment by Dis90** [comment]
@PiotrMachowski Thanks for explanation. I updated translation and now it's complete.

**Comment by PiotrMachowski** [comment]
Thank you @Dis90!

**Pull request merged**
