### PR TITLE
add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by LeandroIssa**
Please add the Brazilian Portuguese translation.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
Don't worry about failing builds, I will fix it :)

**Comment by LeandroIssa** [comment]
> Don't worry about failing builds, I will fix it :)

Thanks so much for the help, I really have no idea what the error might be!

**Comment by LeandroIssa** [comment]
> @LeandroIssa please merge this PR: [LeandroIssa#1](https://github.com/LeandroIssa/lovelace-xiaomi-vacuum-map-card/pull/1)

How do I do that? I have no idea, it's the second time I've done something around here!

**Comment by PiotrMachowski** [comment]
Ok, I have managed to do it 👍 Thanks!

**Pull request merged**
