### PR TITLE
vacuum_goto and vacuum_follow_path modes for Tasshack/dreame-vacuum

### PR DESCRIPTION
**Pull request by Tasshack**
Compatibility with [v2.0.0](https://github.com/Tasshack/dreame-vacuum/releases/tag/v2.0.0b9)

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
Thanks, @Tasshack!

**Comment by jlssmt** [comment]
@PiotrMachowski when this will be released? :-)

**Comment by PiotrMachowski** [comment]
> I guess this project has been abandoned...

Well, I suppose got a little burned out. I wanted to adjust Map Extractor before releasing Map Card, but it turned out to be a bit more time demanding then I could handle recently. The upside is that you can still manually configure every aspect of this card, so it is possible to add these features to your own HA

**Comment by PiotrMachowski** [comment]
You can just copy and paste config from your PR. Here is a config that adds all features from this PR:

```yaml
type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.dreame
calibration_source:
  camera: true
entity: vacuum.dreame
vacuum_platform: Tasshack/dreame-vacuum
map_modes:
  - template: vacuum_clean_zone
  - template: vacuum_clean_point
  - name: Go to point
    icon: mdi:map-marker-radius
    selection_type: MANUAL_POINT
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    repeats_type: NONE
    max_repeats: 0
    max_selections: 1
    service_call_schema:
      service: dreame_vacuum.vacuum_goto
      service_data:
        x: '[[point_x]]'
        'y': '[[point_y]]'
        entity_id: '[[entity_id]]'
  - name: Go To Predefined
    icon: mdi:map-marker-multiple
    selection_type: PREDEFINED_POINT
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    repeats_type: NONE
    max_repeats: 0
    max_selections: 1
    service_call_schema:
      service: dreame_vacuum.vacuum_goto
      service_data:
        x: '[[point_x]]'
        'y': '[[point_y]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
  - name: Follow path
    icon: mdi:map-marker-path
    selection_type: MANUAL_PATH
    coordinates_rounding: true
    coordinates_to_meters_divider: 1000
    repeats_type: NONE
    max_repeats: 0
    max_selections: 20
    service_call_schema:
      service: dreame_vacuum.vacuum_follow_path
      service_data:
        points: '[[selection]]'
        entity_id: '[[entity_id]]'
```

**Pull request merged**
